/**
 * @author José Martins
 */

package quotasmanager;

public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form QuotasJFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        MenuBar = new javax.swing.JMenuBar();
        AdicionarNovoSocio = new javax.swing.JMenu("Adicionar Novo Sócio");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(jTable1);

        AdicionarNovoSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarNovoSocioActionPerformed(evt);
            }
        });
        MenuBar.add(AdicionarNovoSocio);
        AdicionarNovoSocio.getAccessibleContext().setAccessibleDescription("");

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdicionarNovoSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarNovoSocioActionPerformed
        new NovoSocioFrame().setVisible(true);
    }//GEN-LAST:event_AdicionarNovoSocioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new MainFrame().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AdicionarNovoSocio;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
